# Base Alpine Linux based image with OpenJDK JRE only
FROM openjdk:8-jre-alpine
# copy application WAR (with libraries inside)
COPY target/springbootapp-*.jar /app.jar
# copy secret key to connect to Google Cloud SQL 
COPY src/main/resources/creds.json /creds.json
# Set Environment variables
ENV GOOGLE_APPLICATION_CREDENTIALS=creds.json
# specify default command
CMD ["/usr/bin/java", "-jar", "/app.jar"]