# Base Alpine Linux based image with OpenJDK JRE only
FROM openjdk:8-jre-alpine
# copy application WAR (with libraries inside)
COPY target/springbootapp-*.jar /app.jar
# Environment variables
#ENV GOOGLE_APPLICATION_CREDENTIALS=/C/Users/Deepu/eclipse-workspace/springbootapp/src/main/resources/springbootapp-222004-c5a98d98dd78.json
# specify default command
CMD ["/usr/bin/java", "-jar", "/app.jar"]